//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoRendicion
    {
        public int DocumentoRendicionId { get; set; }
        public int DocumentoId { get; set; }
        public int NumeroRendicion { get; set; }
        public string Serie { get; set; }
        public string Correlativo { get; set; }
        public double MontoDocumento { get; set; }
        public double MontoTasaCambio { get; set; }
        public double MontoNoAfecto { get; set; }
        public double MontoAfecto { get; set; }
        public double MontoIgv { get; set; }
        public double MontoTotal { get; set; }
        public int EstadoRendicion { get; set; }
        public System.DateTime FechaDocumento { get; set; }
        public string SapBusinessPartnerCardCode { get; set; }
        public string C_1SapCentroCostoOcrCode { get; set; }
        public string C_2SapCentroCostoOcrCode { get; set; }
        public string C_3SapCentroCostoOcrCode { get; set; }
        public string C_4SapCentroCostoOcrCode { get; set; }
        public string C_5SapCentroCostoOcrCode { get; set; }
        public string SapMonedaDocCurrCod { get; set; }
        public int CreacionUsuarioId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int ModificacionUsuarioId { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual SapCentroCosto SapCentroCosto { get; set; }
        public virtual SapCentroCosto SapCentroCosto1 { get; set; }
        public virtual SapCentroCosto SapCentroCosto2 { get; set; }
        public virtual SapCentroCosto SapCentroCosto3 { get; set; }
        public virtual SapCentroCosto SapCentroCosto4 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual SapBusinessPartner SapBusinessPartner { get; set; }
        public virtual SapMoneda SapMoneda { get; set; }
    }
}
