//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documento()
        {
            this.DocumentoRendicion = new HashSet<DocumentoRendicion>();
        }
    
        public int DocumentoId { get; set; }
        public string Codigo { get; set; }
        public string Asunto { get; set; }
        public string Motivo { get; set; }
        public int NumeroRendicion { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public double MontoInicial { get; set; }
        public int TipoDocumentoId { get; set; }
        public string SapBusinessPartnerCardCode { get; set; }
        public string C_1SapCentroCostoOcrCode { get; set; }
        public string C_2SapCentroCostoOcrCode { get; set; }
        public string C_3SapCentroCostoOcrCode { get; set; }
        public string C_4SapCentroCostoOcrCode { get; set; }
        public string C_5SapCentroCostoOcrCode { get; set; }
        public int CreacionUsuarioId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int ModificacionUsuarioId { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual SapCentroCosto SapCentroCosto { get; set; }
        public virtual SapCentroCosto SapCentroCosto1 { get; set; }
        public virtual SapCentroCosto SapCentroCosto2 { get; set; }
        public virtual SapCentroCosto SapCentroCosto3 { get; set; }
        public virtual SapCentroCosto SapCentroCosto4 { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoRendicion> DocumentoRendicion { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual SapBusinessPartner SapBusinessPartner { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
