//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excepcion
    {
        public int idExcepcion { get; set; }
        public string mensaje { get; set; }
        public string tipo { get; set; }
        public string pila { get; set; }
        public string navegador { get; set; }
        public string excepcionInterna { get; set; }
        public string timeStamp { get; set; }
        public string sessionKeys { get; set; }
    }
}
