//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceLine = new HashSet<InvoiceLine>();
            this.Payment = new HashSet<Payment>();
        }
    
        public int InvoiceId { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public string CardCode { get; set; }
        public string Indicator { get; set; }
        public string ControlAccount { get; set; }
        public Nullable<int> Series { get; set; }
        public Nullable<int> DocType { get; set; }
        public string DocCurrency { get; set; }
        public string JOurnalMemo { get; set; }
        public string Comments { get; set; }
        public string PaymentMethod { get; set; }
        public string NumAtCard { get; set; }
        public string FolioPrefixString { get; set; }
        public Nullable<int> FolioNumber { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public Nullable<int> DocSubType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLine> InvoiceLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
