//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NivelAprobacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NivelAprobacion()
        {
            this.UsuarioNivelAprobacion = new HashSet<UsuarioNivelAprobacion>();
        }
    
        public int NivelAprobacionId { get; set; }
        public int TipoDocumentoId { get; set; }
        public int NumeroNivel { get; set; }
        public string Descripcion { get; set; }
    
        public virtual TipoDocumento TipoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioNivelAprobacion> UsuarioNivelAprobacion { get; set; }
    }
}
