//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPCentroCostosUsuario
    {
        public int idSAPCentroCostosUsuario { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idCentroCosto { get; set; }
    
        public virtual SAPCentroCostos SAPCentroCostos { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
