//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPServicio
    {
        public int idSAPServicio { get; set; }
        public string itemCode { get; set; }
        public string itemName { get; set; }
        public string validFor { get; set; }
    }
}
