//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SapTipoCambio
    {
        public int SapTipoCambioId { get; set; }
        public Nullable<System.DateTime> RateDate { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Rate { get; set; }
    }
}
