//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SICEREntities : DbContext
    {
        public SICEREntities()
            : base("name=SICEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Concepto> Concepto { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<DocumentoDetalle> DocumentoDetalle { get; set; }
        public virtual DbSet<Excepcion> Excepcion { get; set; }
        public virtual DbSet<Motivo> Motivo { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<SAPAccount> SAPAccount { get; set; }
        public virtual DbSet<SAPCentroCostos> SAPCentroCostos { get; set; }
        public virtual DbSet<SAPCentroCostosUsuario> SAPCentroCostosUsuario { get; set; }
        public virtual DbSet<SAPCuentasContables> SAPCuentasContables { get; set; }
        public virtual DbSet<SAPMetodoPago> SAPMetodoPago { get; set; }
        public virtual DbSet<SAPMoneda> SAPMoneda { get; set; }
        public virtual DbSet<SAPProveedor> SAPProveedor { get; set; }
        public virtual DbSet<SAPServicio> SAPServicio { get; set; }
        public virtual DbSet<TipoDocumentoOrigen> TipoDocumentoOrigen { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioRol> UsuarioRol { get; set; }
        public virtual DbSet<UsuarioTipoDocumento> UsuarioTipoDocumento { get; set; }
        public virtual DbSet<UsuarioUsuariosAprobacion> UsuarioUsuariosAprobacion { get; set; }
        public virtual DbSet<Vistas> Vistas { get; set; }
        public virtual DbSet<VistasGrupo> VistasGrupo { get; set; }
        public virtual DbSet<VistasRol> VistasRol { get; set; }
    
        public virtual ObjectResult<SP_SAPProveedor_Result> SP_SAPProveedor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAPProveedor_Result>("SP_SAPProveedor");
        }
    }
}
