//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SICEREntities : DbContext
    {
        public SICEREntities()
            : base("name=SICEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AprobacionDocumento> AprobacionDocumento { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<DocumentoRendicion> DocumentoRendicion { get; set; }
        public virtual DbSet<Excepcion> Excepcion { get; set; }
        public virtual DbSet<GrupoVista> GrupoVista { get; set; }
        public virtual DbSet<NivelAprobacion> NivelAprobacion { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<SapBusinessPartner> SapBusinessPartner { get; set; }
        public virtual DbSet<SapCentroCosto> SapCentroCosto { get; set; }
        public virtual DbSet<SapConcepto> SapConcepto { get; set; }
        public virtual DbSet<SapCuentaContable> SapCuentaContable { get; set; }
        public virtual DbSet<SapIndicators> SapIndicators { get; set; }
        public virtual DbSet<SapMoneda> SapMoneda { get; set; }
        public virtual DbSet<SapTipoCambio> SapTipoCambio { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioNivelAprobacion> UsuarioNivelAprobacion { get; set; }
        public virtual DbSet<UsuarioRoles> UsuarioRoles { get; set; }
        public virtual DbSet<Vista> Vista { get; set; }
        public virtual DbSet<VistaRol> VistaRol { get; set; }
        public virtual DbSet<AggregatedCounter> AggregatedCounter { get; set; }
        public virtual DbSet<Counter> Counter { get; set; }
        public virtual DbSet<Hash> Hash { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JobParameter> JobParameter { get; set; }
        public virtual DbSet<JobQueue> JobQueue { get; set; }
        public virtual DbSet<List> List { get; set; }
        public virtual DbSet<Schema> Schema { get; set; }
        public virtual DbSet<Server> Server { get; set; }
        public virtual DbSet<Set> Set { get; set; }
        public virtual DbSet<State> State { get; set; }
    
        public virtual ObjectResult<SP_SAPProveedor_Result> SP_SAPProveedor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAPProveedor_Result>("SP_SAPProveedor");
        }
    }
}
