//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioTipoDocumento
    {
        public int idUsuarioTipoDocumento { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idTipoDocumento { get; set; }
        public Nullable<int> cantidadDocumentos { get; set; }
        public Nullable<int> idUsuarioUsuariosAprobacion { get; set; }
    
        public virtual TipoDocumentoOrigen TipoDocumentoOrigen { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual UsuarioUsuariosAprobacion UsuarioUsuariosAprobacion { get; set; }
    }
}
