//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioUsuariosAprobacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuarioUsuariosAprobacion()
        {
            this.UsuarioTipoDocumento = new HashSet<UsuarioTipoDocumento>();
        }
    
        public int idUsuarioUsuarioAprobacion { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idUsuarioAprobacion { get; set; }
        public Nullable<int> idTipoDocumentoOrigen { get; set; }
    
        public virtual TipoDocumentoOrigen TipoDocumentoOrigen { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioTipoDocumento> UsuarioTipoDocumento { get; set; }
    }
}
