//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioTipoDocumento
    {
        public int UsuarioTipoDocumentoId { get; set; }
        public int CantidadMaximaDocumentos { get; set; }
        public int UsuarioId { get; set; }
        public int TipoDocumentoId { get; set; }
    
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
