//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Documento1 = new HashSet<Documento>();
            this.Documento2 = new HashSet<Documento>();
            this.DocumentoDetalle = new HashSet<DocumentoDetalle>();
            this.DocumentoDetalle1 = new HashSet<DocumentoDetalle>();
            this.SAPCentroCostosUsuario = new HashSet<SAPCentroCostosUsuario>();
            this.UsuarioRol = new HashSet<UsuarioRol>();
            this.UsuarioTipoDocumento = new HashSet<UsuarioTipoDocumento>();
            this.UsuarioUsuariosAprobacion = new HashSet<UsuarioUsuariosAprobacion>();
            this.UsuarioUsuariosAprobacion1 = new HashSet<UsuarioUsuariosAprobacion>();
        }
    
        public int idUsuario { get; set; }
        public Nullable<int> idRol { get; set; }
        public string username { get; set; }
        public string documento { get; set; }
        public byte[] password { get; set; }
        public string nombres { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public Nullable<bool> estado { get; set; }
        public string userCreate { get; set; }
        public Nullable<bool> enviarCorreoMigracionDo_cumentos { get; set; }
        public Nullable<bool> esUsuarioSAP { get; set; }
        public string cardCodeSAP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documento> Documento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documento> Documento2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoDetalle> DocumentoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoDetalle> DocumentoDetalle1 { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAPCentroCostosUsuario> SAPCentroCostosUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioTipoDocumento> UsuarioTipoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioUsuariosAprobacion> UsuarioUsuariosAprobacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioUsuariosAprobacion> UsuarioUsuariosAprobacion1 { get; set; }
    }
}
