//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistasRol
    {
        public int idVistaRol { get; set; }
        public Nullable<int> idVista { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Vistas Vistas { get; set; }
    }
}
