SELECT CardCode, CardName, CardType,validFor   from [SBO_TAWA_CONSULTING_SAC]..OCRD								--BUSINESS PARTNERS
--SELECT Code, Name, U_CUENTACONTABLE, U_DESCRIPCION  FROM [SBO_TAWA_CONSULTING_SAC]..[@MSS_SICER_CCPT]			--CONCEPTOS
--SELECT OcrCode, OcrName, DimCode, Locked   FROM [SBO_TAWA_CONSULTING_SAC]..OOCR									--CENTRO DE COSTOS
--SELECT DocCurrCod, CurrName, Locked  FROM [SBO_TAWA_CONSULTING_SAC]..OCRN										--MONEDAS
--SELECT Code, Name, U_CODIGO, U_CUENTACONTABLE, U_DESCRIPCION  FROM [SBO_TAWA_CONSULTING_SAC]..[@MSS_SICER_ACCT]	--CUENTAS CONTABLES
--SELECT Code, Name FROM [SBO_TAWA_CONSULTING_SAC]..OIDC															--INDICATORS
--SELECT RateDate, Currency, Rate, * FROM [SBO_TAWA_CONSULTING_SAC]..ORTT											--CAMBIOMONEDA
 


